### ISSUE TITLE
Storybook Build Fails

### ISSUE THREAD

**Issue by nobleach** [lmachens/vite-boilerplate#18]
I don't know if you've noticed but pulling this repo as is, and after installing all dependencies, `npm run build` fails with: 

```bash
> build-storybook -o dist/storybook

info @storybook/react v6.4.22
info
info => Cleaning outputDir: /Users/jimwharton/work/cl-vite/dist/storybook
info => Loading presets
ERR! TypeError: (intermediate value) is not iterable
ERR!     at Object.viteFinal (/Users/jimwharton/work/cl-vite/.storybook/main.js:1:1)
ERR!     at /Users/jimwharton/work/cl-vite/node_modules/@storybook/core-common/dist/cjs/presets.js:279:28
ERR!  TypeError: (intermediate value) is not iterable
ERR!     at Object.viteFinal (/Users/jimwharton/work/cl-vite/.storybook/main.js:1:1)
ERR!     at /Users/jimwharton/work/cl-vite/node_modules/@storybook/core-common/dist/cjs/presets.js:279:28
```

I realize there have been some updates to some packages, so maybe there are version inconsistencies. Most notably, `storybook-builder-vite` has changed names. I'll work to upgrade these and if this works, I'll submit a PR back to you.

But otherwise, have you noticed this?

**Comment by lmachens** [comment]
Hi, a pull request would be highly welcome :). 
I didn't notice it.
